version: 3
services:
  grafana:
    image: grafana/grafana-oss
    ports: 3000:3000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml:Z
      - grafana-data:/var/lib/grafana:Z
  prometheus:
    image: prom/prometheus
    ports: 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - prometheus_data:/prometheus:Z
      - ./rules.yml:/etc/prometheus/rules.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  metrics:
    image: littleangryclouds/prometheus-data-generator
    ports: 9000:9000
    volumes:
      - ./metrics-config.yml:/home/appuser/config.yml:Z
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    privileged: true
    restart: always
volumes:
  grafana_data: {}
  prometheus_data: {}
