---
config:
  - name: oauth_server_requests_total
    description: oauth requests
    type: counter
    labels:
      - container
      - code
    sequence:
      - eval_time: 1
        values: 1-50
        operation: inc
        labels:
          container: oauth-server
          code: 500
      - eval_time: 1
        values: 2000-5000
        operation: inc
        labels:
          container: oauth-server
          code: 200
